/**
 * @file app_config.h
 * @brief Application configuration definitions
 *
 * Maps Kconfig options to application constants.
 */

#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

/* WiFi Configuration */
#define APP_WIFI_SSID      CONFIG_ROBOT_WIFI_SSID
#define APP_WIFI_PASSWORD  CONFIG_ROBOT_WIFI_PASSWORD
#define APP_WIFI_MAX_RETRY CONFIG_ROBOT_WIFI_MAX_RETRY

/* Motor GPIO Pins */
#define APP_MOTOR_LEFT_IN1  CONFIG_ROBOT_MOTOR_LEFT_IN1
#define APP_MOTOR_LEFT_IN2  CONFIG_ROBOT_MOTOR_LEFT_IN2
#define APP_MOTOR_RIGHT_IN1 CONFIG_ROBOT_MOTOR_RIGHT_IN1
#define APP_MOTOR_RIGHT_IN2 CONFIG_ROBOT_MOTOR_RIGHT_IN2
#define APP_MOTORS_ENABLE   CONFIG_ROBOT_MOTORS_ENABLE

/* PWM Configuration */
#define APP_PWM_FREQUENCY  CONFIG_ROBOT_PWM_FREQUENCY
#define APP_PWM_RAMP_MS    CONFIG_ROBOT_PWM_RAMP_DURATION_MS
#define APP_PWM_RAMP_STEPS CONFIG_ROBOT_PWM_RAMP_STEPS

/* Servo Configuration */
#define APP_SERVO_GPIO        CONFIG_ROBOT_SERVO_GPIO
#define APP_SERVO_MIN_PULSE   CONFIG_ROBOT_SERVO_MIN_PULSE_US
#define APP_SERVO_MAX_PULSE   CONFIG_ROBOT_SERVO_MAX_PULSE_US
#define APP_SERVO_MIN_ANGLE   CONFIG_ROBOT_SERVO_MIN_ANGLE
#define APP_SERVO_MAX_ANGLE   CONFIG_ROBOT_SERVO_MAX_ANGLE
#define APP_SERVO_DEFAULT     CONFIG_ROBOT_SERVO_DEFAULT_ANGLE
#define APP_SERVO_STEP        CONFIG_ROBOT_SERVO_STEP_ANGLE
#define APP_SERVO_SMOOTH_STEP CONFIG_ROBOT_SERVO_SMOOTH_STEP
#define APP_SERVO_SMOOTH_MS   CONFIG_ROBOT_SERVO_SMOOTH_DELAY_MS

/* Safety Timeouts */
#define APP_MOVEMENT_TIMEOUT CONFIG_ROBOT_MOVEMENT_TIMEOUT_MS
#define APP_TURRET_TIMEOUT   CONFIG_ROBOT_TURRET_TIMEOUT_MS
#define APP_WATCHDOG_TIMEOUT CONFIG_ROBOT_WATCHDOG_TIMEOUT_S

/* HTTP Server */
#define APP_HTTP_PORT CONFIG_ROBOT_HTTP_PORT
#ifdef CONFIG_ROBOT_ENABLE_MOCK_MODE
#define APP_MOCK_MODE 1
#else
#define APP_MOCK_MODE 0
#endif

/* Camera Configuration */
#define APP_CAMERA_FRAME_SIZE   CONFIG_ROBOT_CAMERA_FRAME_SIZE
#define APP_CAMERA_JPEG_QUALITY CONFIG_ROBOT_CAMERA_JPEG_QUALITY
#define APP_CAMERA_FB_COUNT     CONFIG_ROBOT_CAMERA_FB_COUNT

/* ESP32-S3-CAM Camera Pin Definitions */
#define APP_CAM_PIN_PWDN  -1
#define APP_CAM_PIN_RESET -1
#define APP_CAM_PIN_XCLK  0
#define APP_CAM_PIN_SIOD  26
#define APP_CAM_PIN_SIOC  27
#define APP_CAM_PIN_D7    35
#define APP_CAM_PIN_D6    34
#define APP_CAM_PIN_D5    39
#define APP_CAM_PIN_D4    36
#define APP_CAM_PIN_D3    21
#define APP_CAM_PIN_D2    19
#define APP_CAM_PIN_D1    18
#define APP_CAM_PIN_D0    5
#define APP_CAM_PIN_VSYNC 25
#define APP_CAM_PIN_HREF  23
#define APP_CAM_PIN_PCLK  22

/* LED Configuration */
#define APP_LED_GPIO 4

/* SPIFFS Configuration */
#define APP_SPIFFS_BASE_PATH "/spiffs"
#define APP_SPIFFS_MAX_FILES 5

#ifdef __cplusplus
}
#endif

#endif /* APP_CONFIG_H */
